### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by dirkroorda** [mr-martian/hbo-UD#2]
Hi Daniel  (@mr-martian),

nice to get to know this repo, and thanks for linking back to the BHSA source!

I noticed your [annotation decisions page](https://github.com/mr-martian/hbo-UD/blob/master/Annotation_Decisions.md).

If you wish I'll invite you to the ETCBC slack, where you can discuss data issues with the people who have created the data. 
Alternatively, and probably better, you could use our GitHub discussion page in the BHSA repository (just created!).

If you want a slack invite, mail me at the address you find on my profile: https://pure.knaw.nl/portal/en/persons/dirk-roorda. 

Best, Dirk

**Comment by mr-martian** [comment]
replied by email
